const euro=v=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);
const state={
 settings:{raisonSociale:'Aster Ingénierie Conseil SAS',exercice:'2026',dateCloture:'2026-12-31',activite:'Ingénierie et études techniques',dirigeant:'Président assimilé salarié',resultatProvisoire:120000,tresorerieDisponible:95000,remunerationDejaVersee:29000,salaireConjoint:26000,revenusLMNP:9800,partsFoyer:2,autresRevenus:3500,objectif:'equilibre'},
 params:{isReducedRate:.15,isReducedCeiling:42500,isNormalRate:.25,employerContribRate:.42,employeeContribRate:.22,salaryIrAllowanceRate:.1,lmnpTaxRate:.17,quarterValidationThreshold:1800,scoreWeights:{net:25,cost:20,is:15,ir:10,treasury:20,social:10}},
 scenarios:[{id:'s1',nom:'Prudence trésorerie',remunerationComplementaire:18000},{id:'s2',nom:'Équilibre cabinet',remunerationComplementaire:32000},{id:'s3',nom:'Max net dirigeant',remunerationComplementaire:42000}],
};
const save=()=>localStorage.setItem('arbitrage-sas-v2',JSON.stringify(state));
const load=()=>{const d=localStorage.getItem('arbitrage-sas-v2');if(d)Object.assign(state,JSON.parse(d));};
const isCalc=r=>r<=0?0:Math.min(r,state.params.isReducedCeiling)*state.params.isReducedRate+Math.max(0,r-state.params.isReducedCeiling)*state.params.isNormalRate;
const irCalc=base=>{const t=base/Math.max(1,state.settings.partsFoyer);const b=[[0,11497,0],[11498,29315,.11],[29316,83823,.3],[83824,180294,.41],[180295,1e12,.45]];let x=0;for(const [f,to,r]of b){x+=Math.max(0,Math.min(t,to)-f)*r;}return x*Math.max(1,state.settings.partsFoyer)};
const compute=s=>{const brut=s.remunerationComplementaire,pat=brut*state.params.employerContribRate,sal=brut*state.params.employeeContribRate,net=brut-sal,cout=brut+pat,res=state.settings.resultatProvisoire-cout,isN=isCalc(res);const ir=irCalc((state.settings.remunerationDejaVersee+brut)*(1-state.params.salaryIrAllowanceRate)+state.settings.salaireConjoint+state.settings.revenusLMNP+state.settings.autresRevenus)+state.settings.revenusLMNP*state.params.lmnpTaxRate;const tri=Math.min(4,Math.floor((state.settings.remunerationDejaVersee+brut)/state.params.quarterValidationThreshold));const tres=state.settings.tresorerieDisponible-cout-isN;let score=(net/60000)*25+(1-cout/state.settings.resultatProvisoire)*20+(1-isN/state.settings.resultatProvisoire)*15+(1-ir/40000)*10+(Math.max(0,tres)/state.settings.tresorerieDisponible)*20+(tri/4)*10;return{...s,net,cout,is:isN,ir,res,tres,tri,score:Math.max(0,Math.min(100,score))}}
const all=()=>state.scenarios.map(compute).sort((a,b)=>b.score-a.score);
function render(){
 const sections=['dashboard','dossier','parametres','scenarios','comparaison','visualisations','synthese','annexes'];
 nav.innerHTML=sections.map(s=>`<button onclick="document.getElementById('${s}').scrollIntoView({behavior:'smooth'})">${s[0].toUpperCase()+s.slice(1)}</button>`).join('');
 const rows=all(),best=rows[0];
 dashboard.innerHTML=`<h2>Dashboard</h2><div class="grid"><div class="kpi"><small>Résultat provisoire</small><h3>${euro(state.settings.resultatProvisoire)}</h3></div><div class="kpi"><small>IS estimé</small><h3>${euro(best.is)}</h3></div><div class="kpi"><small>Net dirigeant</small><h3>${euro(best.net)}</h3></div><div class="kpi"><small>Impact trésorerie</small><h3>${euro(best.tres)}</h3></div></div>`;
 dossier.innerHTML=`<h2>Dossier</h2><div class='form'>${['raisonSociale','activite','resultatProvisoire','tresorerieDisponible','remunerationDejaVersee','salaireConjoint','revenusLMNP','partsFoyer','autresRevenus'].map(k=>`<label>${k}<input value="${state.settings[k]}" onchange="state.settings['${k}']=isNaN(this.value)?this.value:Number(this.value);save();render()"></label>`).join('')}</div>`;
 parametres.innerHTML=`<h2>Paramètres de calcul</h2><div class='form'>${['isReducedRate','isReducedCeiling','isNormalRate','employerContribRate','employeeContribRate','salaryIrAllowanceRate','lmnpTaxRate','quarterValidationThreshold'].map(k=>`<label>${k}<input type='number' step='0.01' value="${state.params[k]}" onchange="state.params['${k}']=Number(this.value);save();render()"></label>`).join('')}</div>`;
 scenarios.innerHTML=`<h2>Scénarios</h2><div class='row'><input id='nom' placeholder='Nom'><input id='rem' type='number' placeholder='Rémunération'><button class='primary' onclick="state.scenarios.push({id:crypto.randomUUID(),nom:nom.value,remunerationComplementaire:Number(rem.value)});save();render()">Créer un scénario</button></div><table><tr><th>Nom</th><th>Rémunération</th><th>Score</th></tr>${rows.map(r=>`<tr><td>${r.nom}</td><td>${euro(r.remunerationComplementaire)}</td><td>${r.score.toFixed(1)}</td></tr>`).join('')}</table>`;
 comparaison.innerHTML=`<h2>Comparaison</h2><table><tr><th>Scénario</th><th>Coût société</th><th>Net</th><th>IS</th><th>IR</th><th>Trésorerie</th><th>Trimestres</th><th>Score</th></tr>${rows.map((r,i)=>`<tr><td>${r.nom} ${i===0?'<span class="badge ok">Meilleur</span>':''}</td><td>${euro(r.cout)}</td><td>${euro(r.net)}</td><td>${euro(r.is)}</td><td>${euro(r.ir)}</td><td>${euro(r.tres)}</td><td>${r.tri}/4</td><td>${r.score.toFixed(1)}</td></tr>`).join('')}</table>`;
 const max=Math.max(...rows.map(r=>r.net));
 visualisations.innerHTML=`<h2>Visualisations</h2><div class='chart'>${rows.map(r=>`<div class='bar' style='height:${(r.net/max)*100}%'><span>${r.nom}</span></div>`).join('')}</div>`;
 synthese.innerHTML=`<h2>Note de synthèse imprimable</h2><p>${state.settings.raisonSociale} — Exercice ${state.settings.exercice}</p><p>Scénario préconisé : <b>${best.nom}</b> (score ${best.score.toFixed(1)}/100)</p><p>Points de vigilance : ${best.tres<0?'trésorerie tendue':'RAS majeur'} ; ${best.tri<4?'trimestres incomplets':'trimestres validés'}.</p>`;
 annexes.innerHTML=`<h2>Annexes techniques</h2><pre>${JSON.stringify({settings:state.settings,params:state.params},null,2)}</pre><p>Formules : coût=brut+charges patronales ; net=brut-charges salariales ; IS par paliers ; IR simplifié ; score pondéré configurable.</p>`;
}
load();render();
